name: Expo Free CD build

on:
  push:
    branches: [main]

jobs:
  build-free-previews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Setup Expo & EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.SOCIALRN_EXPO_TOKEN }}

      - name: Build Android APK & iOS Simulator App
        run: eas build --profile preview --platform all --non-interactive