name: React Native CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
    
      - name: Install JS Dependencies
        run: npm install
      
      - name: Run Linter
        run: npm run lint --if-present
      
      - name: Check TypeScript Types
        run: npm run typecheck --if-present

      - name: Run Unit Tests
        run: npm test -- --watchAll=false